cmd /c code --install-extension waderyan.nodejs-extension-pack
cmd /c code --install-extension alefragnani.numbered-bookmarks
cmd /c code --install-extension abusaidm.html-snippets
cmd /c code --install-extension clinyong.vscode-css-modules
cmd /c code --install-extension cssho.vscode-svgviewer
cmd /c code --install-extension dkundel.vscode-npm-source
cmd /c code --install-extension donjayamanne.githistory
cmd /c code --install-extension DotJoshJohnson.xml
cmd /c code --install-extension ecmel.vscode-html-css
cmd /c code --install-extension formulahendry.auto-close-tag
cmd /c code --install-extension formulahendry.code-runner
cmd /c code --install-extension hbenl.vscode-firefox-debug
cmd /c code --install-extension IBM.output-colorizer
cmd /c code --install-extension joelday.docthis
cmd /c code --install-extension marcostazi.VS-code-vagrantfile
cmd /c code --install-extension michelemelluso.code-beautifier
cmd /c code --install-extension minhthai.vscode-todo-parser
cmd /c code --install-extension mrcrowl.hg
cmd /c code --install-extension mrmlnc.vscode-less
cmd /c code --install-extension ms-vscode.csharp
cmd /c code --install-extension ms-vscode.PowerShell
cmd /c code --install-extension msjsdiag.debugger-for-chrome
cmd /c code --install-extension naumovs.color-highlight
cmd /c code --install-extension PeterJausovec.vscode-docker
cmd /c code --install-extension pranaygp.vscode-css-peek
cmd /c code --install-extension qinjia.view-in-browser
cmd /c code --install-extension ronnidc.nunjucks
cmd /c code --install-extension sidthesloth.html5-boilerplate
cmd /c code --install-extension vscodevim.vim
cmd /c code --install-extension waderyan.gitblame
cmd /c code --install-extension wcwhitehead.bootstrap-3-snippets
cmd /c code --install-extension xabikos.JavaScriptSnippets

cmd /c code --install-extension jeremyrajan.webpack
cmd /c code --install-extension burkeholland.simple-react-snippets
cmd /c code --install-extension chrmarti.regex
cmd /c code --install-extension ricard.postcss
cmd /c code --install-extension christian-kohler.path-intellisense
cmd /c code --install-extension dasfranck.jellybeans
cmd /c code --install-extension sidneys1.gitconfig
cmd /c code --install-extension donjayamanne.githistory
cmd /c code --install-extension editorconfig.editorconfig
cmd /c code --install-extension wmaurer.change-case