cmd /c code --uninstall-extension waderyan.nodejs-extension-pack
cmd /c code --uninstall-extension alefragnani.numbered-bookmarks
cmd /c code --uninstall-extension abusaidm.html-snippets
cmd /c code --uninstall-extension clinyong.vscode-css-modules
cmd /c code --uninstall-extension cssho.vscode-svgviewer
cmd /c code --uninstall-extension dkundel.vscode-npm-source
cmd /c code --uninstall-extension donjayamanne.githistory
cmd /c code --uninstall-extension DotJoshJohnson.xml
cmd /c code --uninstall-extension ecmel.vscode-html-css
cmd /c code --uninstall-extension formulahendry.auto-close-tag
cmd /c code --uninstall-extension formulahendry.code-runner
cmd /c code --uninstall-extension hbenl.vscode-firefox-debug
cmd /c code --uninstall-extension IBM.output-colorizer
cmd /c code --uninstall-extension joelday.docthis
cmd /c code --uninstall-extension marcostazi.VS-code-vagrantfile
cmd /c code --uninstall-extension michelemelluso.code-beautifier
cmd /c code --uninstall-extension minhthai.vscode-todo-parser
cmd /c code --uninstall-extension mrcrowl.hg
cmd /c code --uninstall-extension mrmlnc.vscode-less
cmd /c code --uninstall-extension ms-vscode.csharp
cmd /c code --uninstall-extension ms-vscode.PowerShell
cmd /c code --uninstall-extension msjsdiag.debugger-for-chrome
cmd /c code --uninstall-extension naumovs.color-highlight
cmd /c code --uninstall-extension PeterJausovec.vscode-docker
cmd /c code --uninstall-extension pranaygp.vscode-css-peek
cmd /c code --uninstall-extension qinjia.view-in-browser
cmd /c code --uninstall-extension ronnidc.nunjucks
cmd /c code --uninstall-extension sidthesloth.html5-boilerplate
cmd /c code --uninstall-extension vscodevim.vim
cmd /c code --uninstall-extension waderyan.gitblame
cmd /c code --uninstall-extension wcwhitehead.bootstrap-3-snippets
cmd /c code --uninstall-extension xabikos.JavaScriptSnippets